baseURL = "https://tricht.dev/"
languageCode = "en-us"
title = "Michael's blog"
theme = "hyde"
Paginate = 5
publishDir = "docs"
[params]
  themeColor = "theme-base-0c"

[blackfriday]
  hrefTargetBlank = true
